# Generated by Django 2.0.2 on 2018-05-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180516_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(max_length='1000'),
        ),
    ]
